Admin_Interface/Models/Species.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Globalization;
using System.Linq;
using System.Web;

namespace Admin_Interface.Models
{
    public class Species 
    {
        [Key]
		public int Id { get; set; }

		[Display(Name = "Nom")]
		public string Name { get; set; }

		[Display(Name = "Nom Latin")]
		public string LatinName { get; set; }

		[Display(Name = "Description")]
		public string Description { get; set; }

		[Display(Name = "Début de la période")]
		public int PeriodBegin { get; set; }

		[Display(Name = "Fin de la période")]
		public int PeriodEnd { get; set; }

		[Display(Name = "Genre")]
		public int GenderId { get; set; }

		public int StatusId { get; set; }

		public int PublisherId { get; set; }

	}
}

Admin_Interface/Models/User.cs
using Admin_Interface.Tools;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Admin_Interface.Models
{
    public class User
    {
        [ReadOnly(true)]
        public int Id { get; set; }

        [Display(Name = "Nom")]
        public string Name { get; set; }

        [Display(Name = "Prénom")]
        public string LastName { get; set; }

        [Display(Name = "E-Mail")]
        public string Email { get; set; }

        [HiddenInput]
        public string Login { get; set; }

        [HiddenInput]
        [Display(Name = "Mot de passe")]
        public string Pwd { get; set; }

        [HiddenInput]
        public bool Active { get; set; }

        [Display(Name = "Actif")]
        public string IsActive
        {
            get { return Active.ToOuiNon(); }
        }

        [HiddenInput]
        public int RoleId { get; set; }

        [Display(Name = "Role")]
        public string RoleType { get; set; }

    }
}

Admin_Interface/Models/ViewModels/UserViews/UserForm.cs
using Admin_Interface.Tools;
using DAL_Client.Services;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Admin_Interface.Models.ViewModels.UserViews
{
    public class UserForm
    {
		private User _user;

		private List<Role> _roles;

		[Display(Name = "Rôle")]
		public List<Role> Roles
		{
			get
			{
				RoleService service = new RoleService();
				_roles = service.GetAll().Select(r => r.ToASP()).ToList();
				return _roles;
			}
			private set => _roles = value;
		}

		[Display(Name = "Nom")]
        public string Name 
        {
            get => _user.Name;
            set => _user.Name = value;
        }

        [Display(Name = "Prénom")]
        public string LastName 
        {
            get => _user.LastName;
            set => _user.LastName = value;
        }

        [Display(Name = "Login")]
        public string Login 
        {
            get => _user.Login;
            set => _user.Login = value;
        }

        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Un mot de passe est requis")]
        [Display(Name = "Mot de passe")]
        public string Pwd 
        {
            get => _user.Pwd;
            set => _user.Pwd = value;
        }

        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "Une adresse e-mail est requise")]
        [Display(Name = "E-Mail")]
        public string Email 
        {
            get => _user.Email;
            set => _user.Email = value;
        }

        [HiddenInput(DisplayValue = false)]
        public string RoleType 
        {
            get => _user.RoleType;
            set => _user.RoleType = value; 
        }

		[HiddenInput(DisplayValue = false)]
		public int RoleId
		{
			get => _user.RoleId;
			set => _user.RoleId = value;
		}

		[HiddenInput(DisplayValue = false)]
		public bool Active
		{
			get => _user.Active;
			set => _user.Active = value;
		}

		public UserForm()
		{
			_user = new User();
		}

		public User SaveUser()
		{   
			UserService service = new UserService();
			_user.Id = service.Insert(_user.ToDC());
			return _user;
		}
    }
}

Admin_Interface/Controllers/DashBoardController.cs
using Admin_Interface.Models;
using Admin_Interface.Models.ViewModels.SpeciesViews;
using Admin_Interface.Models.ViewModels.UserViews;
using Admin_Interface.Tools;
using DAL_Client.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Admin_Interface.Controllers
{
    //[AuthRequired]
    public class DashBoardController : Controller
    {
        // GET: DashBoard
        [HttpGet]
        public ActionResult Index()
        {
            // SuperAdmin
            if (UserSession.AuthUser.RoleId == 1)
            {
				// nombre de fiches
				SpeciesService spService = new SpeciesService();
				List<Species> species = spService.GetAll().Select(s => s.ToASP()).Where(s => s.Id != 1).ToList();

				int spTotal = species.Count();
				int spDraft = 0;
				int spToTreat = 0;
				int spPublished = 0;

				for (int i = 0; i < spTotal; i++)
				{
					if (species[i].StatusId == 1)
					{
						spToTreat += 1;
					}
					else if (species[i].StatusId == 2)
					{
						spDraft += 1;
					}
					else if (species[i].StatusId == 4)
					{
						spPublished += 1;
					}
				}					
				ViewBag.SpeciesCount = spTotal;
				ViewBag.SpeciesDraft = spDraft;
				ViewBag.SpeciesToTreat = spToTreat;
				ViewBag.SpeciesPublished = spPublished;

				// nombre d'observation
				ObservationService oService = new ObservationService();
				List<ObservationAdmin> observations = oService.GetAll().Select(o => o.ToASP()).ToList();

				int obTotal = observations.Count();
				int obDraft = 0;
				int obValidated = 0;
				int obToTreat = 0;
				int obPublished = 0;

				for (int i = 0; i < obTotal; i++)
				{
					if (observations[i].StatusId == 1)
					{
						obToTreat += 1;
					}
					else if (observations[i].StatusId == 2)
					{
						obDraft += 1;
					}
					else if (observations[i].StatusId == 3)
					{
						obValidated += 1;
					}
					else if (observations[i].StatusId == 4)
					{
						obPublished += 1;
					}
				}

				ViewBag.ObsCount = obTotal;
				ViewBag.ObsDraft = obDraft;
				ViewBag.ObsValidated = obValidated;
				ViewBag.ObsToTreat = obToTreat;
				ViewBag.ObsPublished = obPublished;

				// nombre d'utilisateur
				UserService uService = new UserService();
				List<User> users = uService.GetAll().Select(u => u.ToASP()).ToList();

				int uTotal = users.Count();
				int uSuperAdmin = 0;
				int uAdmin = 0;
				int uAssistant = 0;

				for (int i = 0; i < uTotal; i++)
				{
					if (users[i].RoleId == 1)
					{
						uSuperAdmin += 1;
					}
					else if (users[i].RoleId == 2)
					{
						uAdmin += 1;
					}
					else 
					{
						uAssistant += 1;
					}
				}

				ViewBag.UCount = uTotal;
				ViewBag.USuperAdmin = uSuperAdmin;
				ViewBag.UAdmin = uAdmin;
				ViewBag.UAssistant = uAssistant;

				return View("SuperAdmin");
            }
            return View("Index");
        }

		//TODO : API Weather
		public async Task<ActionResult> ConsumeExternalAPI()
		{
			string token = "APPID=3041cf6b699f3cca03108f762e7c8ffa";
			string baseurl = "http://api.openweathermap.org/data/2.5/weather?q=Ciney&";
			string url = baseurl + token;

			using (HttpClient client = new HttpClient())
			{
				client.BaseAddress = new Uri(url);
				client.DefaultRequestHeaders.Accept.Clear();
				client.DefaultRequestHeaders.Accept.Add(new
				System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));

				System.Net.Http.HttpResponseMessage response = await client.GetAsync(url);
				if (response.IsSuccessStatusCode)
				{
					var data = await response.Content.ReadAsStringAsync();
					var table =
					Newtonsoft.Json.JsonConvert.DeserializeObject<System.Data.DataTable>(data);

					System.Web.UI.WebControls.GridView gView = new
					System.Web.UI.WebControls.GridView();
					gView.DataSource = table;
					gView.DataBind();
					using (System.IO.StringWriter sw = new System.IO.StringWriter())
					{
						using (System.Web.UI.HtmlTextWriter htw = new
						System.Web.UI.HtmlTextWriter(sw))
						{
							gView.RenderControl(htw);
							ViewBag.ReturnedData = sw.ToString();
						}
					}
				}
			}
			return View();
		}

		[HttpGet]
        public ActionResult Users()
        {
			if (UserSession.AuthUser == null || UserSession.AuthUser.RoleId != 1)
			{
				return RedirectToAction("Index", "Login");
			}
			else
			{
				UserService service = new UserService();
				IEnumerable<User> users = service.GetAll().Select(u => u.ToASP());
				return View("Users", users);
			}            
		}

        [HttpGet]
        public ActionResult CreateUser()
        {
            // SuperAdmin
            if (UserSession.AuthUser.RoleId == 1)
            {
                UserForm form = new UserForm();
                return PartialView("_CreateUser", form);
            }
            return RedirectToAction("DashBoard", "Index");
        }

        [HttpPost]
        public ActionResult CreateUser(UserForm form)
        {
			if (!ModelState.IsValid)
			{
				return PartialView("_CreateUser", form);
			}

			User user = form.SaveUser();
			//return PartialView("_UserRowTr", user);
			return RedirectToAction("Users", "DashBoard");
		}

        [HttpGet]
        public ActionResult Deactivate(int id)
        {
			// Désactivation du User (Active = false)
            UserService service = new UserService();
            bool result = service.Deactivate(id);

            if (result)
            {
                // Récupération du User pour update du champ
                User user = new User();
                user = service.Get(id).ToASP();
				return PartialView("_UserRow", user);
			}
			// TODO : Si pas bon, afficher modal
			throw new UnauthorizedAccessException();
		}

        [HttpGet]
        public ActionResult Activate(int id)
        {
            // Activation du User (Active = true)
            UserService service = new UserService();
            bool result = service.Activate(id);

            if (result)
            {
                // Récupération du User pour update du champ
                User user = new User();
                user = service.Get(id).ToASP();
                return PartialView("_UserRow", user);
				// TODO : Si pas bon, afficher modal
            }
			throw new UnauthorizedAccessException();
		}

        [HttpGet]
        public ActionResult Species()
        {
            SpeciesService service = new SpeciesService();
			IEnumerable<SpeciesAdmin> species = service.GetAllDTO().Select(p => p.ToASP());
            return View("Species", species);
        }

		#region Create Species
		[HttpGet]
		public ActionResult CreateSpecies()
		{
			SpeciesForm form = new SpeciesForm();
			// TODO : choper l'Id du publisher par Usersession
			// En attendant, on prend le SA
			form.PublisherId = 1;
			return PartialView("_CreateSpecies", form);
		}

		[HttpPost]
		public ActionResult CreateSpecies(SpeciesForm form)
		{
			SpeciesService service = new SpeciesService();
			Species species = new Species();
			// TODO : Définir le statut en fonction de l'actionName
			// Pour l'instant CreateSpecies = brouillon
			form.StatusId = 2;
			species = form.SaveSpecies();

			SpeciesAdmin sp = new SpeciesAdmin();
			sp = service.GetDTO(species.Id).ToASP();
			return RedirectToAction("SpeciesDetails", "DashBoard", new { id = species.Id });
		}

		//public ActionResult ModifySpecies(int id)
		//{
		//	SpeciesService service = new SpeciesService();
		//	SpeciesForm form = new SpeciesForm();
		//	form = service.Get(id).ToASP();
		//}
			   
		//[HttpGet]
		//public ActionResult Species(int id)
		//{
		//	SpeciesService service = new SpeciesService();
		//	SpeciesAdmin sp = new SpeciesAdmin();
		//	sp = service.GetDTO(id).ToASP();				
		//	return View(sp);
		//}

		[HttpGet]
		public ActionResult SpeciesDetails(int id)
		{
			SpeciesService service = new SpeciesService();
			SpeciesAdmin sp = new SpeciesAdmin();
			sp = service.GetDTO(id).ToASP();
			return View("SpeciesDetails", sp);
		}

        [HttpGet]
        public ActionResult SpeciesTaxonomy(int id)
        {
            SpeciesService service = new SpeciesService();
            SpeciesAdmin sp = new SpeciesAdmin();
            sp = service.GetDTO(id).ToASP();
            return PartialView("_SpeciesTaxo", sp);
        }

        [HttpGet]
        public ActionResult SpeciesImages(int id)
        {
            ImgService service = new ImgService();
            IEnumerable<Img> imgs = service.GetAllImgBySpeciesId(id).Select(i => i.ToASP());
            return PartialView("_SpeciesImages", imgs);
        }

        //[HttpGet]
        //public ActionResult SpeciesAddImages(int id)
        //{ 
            
        //}

		public JsonResult GetKingdoms()
		{
			List<Kingdom> kingdoms = new List<Kingdom>();
			KingdomService service = new KingdomService();
			kingdoms = service.GetAll().Select(k => k.ToASP()).OrderBy(k => k.LatinName).ToList();
			return Json(kingdoms, JsonRequestBehavior.AllowGet);
		}

		public JsonResult GetBranches(int kingdomId)
		{
			List<Branch> branches = new List<Branch>();
			BranchService service = new BranchService();
			branches = service.GetAllBranchByKingdomId(kingdomId).Select(b => b.ToASP()).OrderBy(k => k.LatinName).ToList();
			branches.OrderBy(b => b.LatinName);
			return Json(branches, JsonRequestBehavior.AllowGet);
		}

		public JsonResult GetSubBranches(int branchId)
		{
			List<SubBranch> subBranches = new List<SubBranch>();

			SubBranchService service = new SubBranchService();
			subBranches = service.GetAllSubBranchByBranchId(branchId).Select(b => b.ToASP()).OrderBy(k => k.LatinName).ToList();
			subBranches.OrderBy(s => s.LatinName);

Admin_Interface/Controllers/ImgController.cs
using Admin_Interface.Models;
using Admin_Interface.Tools;
using DAL_Client.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Admin_Interface.Controllers
{
    public class ImgController : Controller
    {
        // GET: Img
        public ActionResult Get(int id)
        {
            ImgService imgService = new ImgService();
            Img img = new Img();
            img = imgService.Get(id).ToASP();
            byte[] imgByteArray = img.Data;
            string arg = "data:image/jpeg;base64,/";
            return File(imgByteArray, arg);
        }
    }
}

Admin_Interface/Views/DashBoard/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>TEST DASHBOARD</p>

Admin_Interface/Views/DashBoard/Species.cshtml
@model IEnumerable<Admin_Interface.Models.ViewModels.SpeciesViews.SpeciesAdmin>
@{
    ViewBag.Title = "Species";
}

@{
    Layout = "~/Views/Shared/_LayoutSA.cshtml";
}

<h3 class="toLeft">Gestion des espèces</h3>
<div class="col-2-1 toLeft">
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Kingdom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Species)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Period)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StatusType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Publisher)
            </th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Kingdom)
                <td>
                    @Html.DisplayFor(modelItem => item.Species)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Period)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StatusType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Publisher)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Détail", "SpeciesDetails", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </table>
      @Html.ActionLink(
        "Ajouter une espèce",
        "CreateSpecies",
        "DashBoard",
        null,
        new { @class = "btn btn-primary", data_toggle = "modal", data_target = "#saCreateSpeciesModal" }
        )
</div>



@*@Html.ActionLink(
    "Ajouter une espèce",
    "CreateSpecies",
    "DashBoard",
    null,
    new { @class = "btn btn-primary"}
    )*@

<div id="saCreateSpeciesModal" class="modal fade hidden-print" tabindex="-1" role="dialog">

    <div class="modal-dialog">
        <div class="modal-content">
        </div>
    </div>
</div>


Admin_Interface/Views/DashBoard/SpeciesDetails.cshtml
@model Admin_Interface.Models.ViewModels.SpeciesViews.SpeciesAdmin

@{
    ViewBag.Title = "SpeciesDetails";
}
@{
    Layout = "~/Views/Shared/_LayoutSA.cshtml";
}

<h3 class="toLeft">Page de l'espèce</h3>

<nav class="marginToLeft internNav">
    @Ajax.ActionLink("Taxonomie", "SpeciesTaxonomy", new { id = Model.Id }, new AjaxOptions
    {
        HttpMethod = "GET",
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "saSpeciesDetails",
        //OnComplete = "your_js_function();"
    },
    new { @class ="internNavItem"}
    )


    @Ajax.ActionLink("Images", "SpeciesImages", new { id = Model.Id }, new AjaxOptions
    {
    HttpMethod = "GET",
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "saSpeciesDetails",
    //OnComplete = "your_js_function();",
    },
    new { @class ="internNavItem"}
    )
</nav>

<div class="col-2-1 toLeft">
    <div id="saSpeciesDetails">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Species)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Species)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.Raw(Model.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Period)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Period)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Publisher)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Publisher)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.StatusType)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.StatusType)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Kingdom)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Kingdom)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Branch)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Branch)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.SubBranch)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SubBranch)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Class)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Class)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Gender)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Gender)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Family)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Family)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Order)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Order)
            </dd>

        </dl>

    </div>
</div>
@Html.ActionLink(
    "Modifier",
    "ModifySpecies",
    "DashBoard",
    new { id = Model.Id },
    new { @class = "btn btn-primary marginToLeft" }
    )




Admin_Interface/Views/DashBoard/SpeciesMainPage.cshtml
@model Admin_Interface.Models.ViewModels.SpeciesViews.SpeciesAdmin

@{
    ViewBag.Title = "SpeciesMainPage";
}

<h2>SpeciesMainPage</h2>

<div>
    <h4>SpeciesAdmin</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Species)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Species)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Period)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Period)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PublisherId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PublisherId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Publisher)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Publisher)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StatusId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StatusId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StatusType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StatusType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Kingdom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kingdom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Branch)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Branch)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SubBranch)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubBranch)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Class)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Class)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Family)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Family)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Order)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Order)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Admin_Interface/Views/DashBoard/Users.cshtml
@model IEnumerable<Admin_Interface.Models.User>

@{
    ViewBag.Title = "Users";
}

@{
    Layout = "~/Views/Shared/_LayoutSA.cshtml";
}
@using Admin_Interface.Tools;

<h3 class="toLeft">Gestion des utilisateurs</h3>

<div class="col-2-1 toLeft">

    <table id="saUsersList" class="table">

        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Login)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pwd)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsActive)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RoleType)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr id="@string.Format("user_{0}", item.Id )">
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Login)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Pwd)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsActive)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RoleType)
                </td>
                <td>
                    @if (item.Id == UserSession.AuthUser.Id)
                    {
                        <span>/</span>
                    }
                    else
                    {
                        if (item.Active == true)
                        {
                            <a class="deactivate" href="@Url.Action("Deactivate","DashBoard", new { Id = item.Id })">Désactiver</a>
                        }
                        else
                        {
                            <a class="activate" href="@Url.Action("Activate","DashBoard", new { Id = item.Id })">Activer</a>
                        }
                    }
                </td>
                @*<td>
                    @Html.ActionLink("Modifier", "Modify", new { id = item.Id })
                </td>
                <td>
                    @Html.ActionLink("Supprimer", "Delete", new { id = item.Id })
                </td>*@
            </tr>
        }
    </table>
    @Html.ActionLink(
    "Ajouter un utilisateur",
    "CreateUser",
    "DashBoard",
    null,
    new { @class = "btn btn-primary", data_toggle = "modal", data_target = "#saCreateUserModal" }
    )
</div>



<div id="saCreateUserModal" class="modal fade hidden-print" tabindex="-1" role="dialog">

    <div class="modal-dialog">
        <div class="modal-content">
        </div>
    </div>
</div>


Admin_Interface/Views/DashBoard/_SpeciesImages.cshtml
@model IEnumerable<Admin_Interface.Models.Img>

@if (Model.Count() > 0)
{
    foreach (var item in Model)
    {
        <div class="saSpeciesImgContainer">
            <img class="saSpeciesImgData" src="@Url.Action("Get", "Img", new { id = item.SpeciesId })" />
            <p>@Html.DisplayFor(modelItem => item.CopyRight)</p>
            @*<a href="#">Supprimer</a>
            <a href="#">Modifier</a>*@
        </div>
    }
}
else
{
    <p>Aucune image n'est disponible pour cette espèce</p>
}

<div class="img">


</div>